name: IOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 14.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Build (Debug, Simulator)
        run: |
          xcodebuild \
            -scheme "KitchenScan" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
            clean build
